language:
    - go

go:
    - 1.6

virtualenv:
    system_site_packages: true

install:
    - export GOPATH=$GOPATH:$HOME/gopath/src/github.com/dkumor/connectordb
    - export PATH=$HOME/.local/bin:$PATH
    - pip install --user nose requests jsonschema websocket-client coverage
    - npm install -g bower
    - make deps

script:
    - make
    - make test

notifications:
    slack: connectordb:3YIEG5E8KpOqaNbScZv0Rs0r
    
    notifications:

webhooks:
    urls:
      - https://webhooks.gitter.im/e/7699dc15edd78aeedf32
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
