language: go
go: 
    - tip

install:
    - export GOPATH=$GOPATH:$HOME/gopath/src/github.com/dkumor/connectordb
    - go get github.com/apcera/nats
    - go get github.com/apcera/gnatsd
    - go get github.com/mattn/go-sqlite3
    - go get github.com/nu7hatch/gouuid
    - go get github.com/gorilla/mux
    
script: go test streamdb/...