language:
    - go
    
go:
    - tip

            
virtualenv:
    system_site_packages: true
  
install:
    - export GOPATH=$GOPATH:$HOME/gopath/src/github.com/dkumor/connectordb
    - export PATH=$HOME/.local/bin:$PATH
    - pip install --user nose requests

script:
    - make
    - make test

notifications:
    slack: connectordb:3YIEG5E8KpOqaNbScZv0Rs0r
