language:
    - go
    - python
go:
    - tip

python:
    - "2.7"

addons:
    postgresql: "9.3"
    apt:
        packages:
            - sqlite3

install:
    - export GOPATH=$GOPATH:$HOME/gopath/src/github.com/dkumor/connectordb
    - pip install nose requests
    - make dependencies

script:
    - make coverage
    - make
    - make test

notifications:
    slack: connectordb:3YIEG5E8KpOqaNbScZv0Rs0r
